blank_issues_enabled: false

contact_links:
  - name: Ask a Question
    url: https://github.com/SkillSageDev/search-engine/discussions
    about: >
      For questions about how the project works, use GitHub Discussions
      instead of filing an issue.
